---------------
---nvim-tree---
---------------
require("user.tools.nvim-tree")
---------------
---telescope---
---------------
require("user.tools.telescope")
---------------
--toggleterm---
---------------
require("user.tools.toggleterm")
---------------
--bufferline---
---------------
require("user.tools.bufferline")
---------------
----comment----
---------------
require("user.tools.comment")
---------------
---dashboard---
---------------
require("user.tools.alpha")
